image: node:16.15.0

pipelines:
  pull-requests:
    release/*:
      - step:
         name: 'Publish to Chromatic'
         caches:
           - node
         script:
           - npm ci
           - npm run chromatic --patch-build=$your-branch...master
