definitions:
  caches:
    pnpm: $BITBUCKET_CLONE_DIR/.pnpm-store

pipelines:
  pull-requests:
    "release/*":
      - step:
          name: Publish to Chromatic
          image: node:16.15.0
          script:
            - npm i pnpm@6.32 -g
            - pnpm install
            - pnpm chromatic --patch-build=$your-branch...master
          caches:
            - pnpm
